# Generated by Django 4.1.7 on 2023-03-22 10:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(default=datetime.datetime.now, verbose_name='date played')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('reg_date', models.DateField(default=datetime.datetime.now, verbose_name='Registration day')),
            ],
        ),
        migrations.CreateModel(
            name='GameResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.IntegerField(default=0)),
                ('milestones_score', models.IntegerField(default=0)),
                ('awards_score', models.IntegerField(default=0)),
                ('tr_score', models.IntegerField(default=0)),
                ('card_score', models.IntegerField(default=0)),
                ('board_score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marstracker.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marstracker.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games', through='marstracker.GameResults', to='marstracker.player'),
        ),
    ]
