# Generated by Django 4.1.7 on 2023-03-08 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('final_score', models.IntegerField(default=0)),
                ('milestones_score', models.IntegerField(default=0)),
                ('awards_score', models.IntegerField(default=0)),
                ('tr_score', models.IntegerField(default=0)),
                ('card_score', models.IntegerField(default=0)),
                ('board_score', models.IntegerField(default=0)),
                ('pub_date', models.DateField(verbose_name='date played')),
            ],
        ),
        migrations.CreateModel(
            name='GameStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marstracker.playerstatistics')),
            ],
        ),
    ]
