# Generated by Django 4.1.7 on 2023-03-09 12:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marstracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('reg_date', models.DateField(default=datetime.datetime(2023, 3, 9, 12, 24, 46, 237242), verbose_name='Registration day')),
            ],
        ),
        migrations.AddField(
            model_name='gamestatistics',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 9, 12, 24, 46, 252414), verbose_name='date played'),
        ),
        migrations.AlterField(
            model_name='gamestatistics',
            name='player',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='player_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marstracker.gamestatistics'),
        ),
    ]
