# Generated by Django 4.1.7 on 2023-03-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marstracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='map_type',
            field=models.CharField(choices=[('S', 'Standard'), ('H', 'Hellas'), ('E', 'Elysium')], default='S', max_length=50),
        ),
    ]
