# Generated by Django 4.1.7 on 2023-03-09 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marstracker', '0002_player_gamestatistics_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestatistics',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='date played'),
        ),
        migrations.AlterField(
            model_name='player',
            name='reg_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Registration day'),
        ),
    ]
