# Generated by Django 4.1.7 on 2023-03-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marstracker', '0002_game_map_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameresults',
            unique_together={('player', 'game')},
        ),
    ]
