# Generated by Django 4.1.7 on 2023-03-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marstracker', '0003_alter_gamestatistics_pub_date_alter_player_reg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstatistics',
            name='player_name',
        ),
        migrations.RemoveField(
            model_name='gamestatistics',
            name='player',
        ),
        migrations.AddField(
            model_name='gamestatistics',
            name='player',
            field=models.ManyToManyField(to='marstracker.player'),
        ),
    ]
