# Generated by Django 4.1.7 on 2023-03-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marstracker', '0004_remove_playerstatistics_player_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestatistics',
            old_name='player',
            new_name='players',
        ),
    ]
