# Generated by Django 4.1.7 on 2023-03-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marstracker', '0005_rename_player_gamestatistics_players'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameStatistics',
            new_name='Game',
        ),
        migrations.DeleteModel(
            name='PlayerStatistics',
        ),
    ]
