# Generated by Django 4.1.7 on 2023-03-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marstracker', '0008_remove_game_game_results_alter_gameresults_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresults',
            name='pub_date',
        ),
    ]
