# Generated by Django 4.1.7 on 2023-03-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marstracker', '0009_remove_gameresults_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='scores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marstracker.gameresults'),
        ),
    ]
